apiVersion: v1
kind: Service
metadata: 
 name: amf-{{ .Release.Name }}-sctp
 labels:
   epc-mode: {{ .Release.Name }}-amf
spec:
 type: NodePort
 selector:
   epc-mode: {{ .Release.Name }}-amf
 ports:
   - protocol: SCTP
     port: 38412
     targetPort: 38412
     nodePort: 30413
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-amf
  labels:
    epc-mode: {{ .Release.Name }}-amf
spec:
  selector:
    epc-mode: {{ .Release.Name }}-amf
  ports:
    - protocol: TCP
      port: 80   
      targetPort: 80      
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-amf-deployment
  labels:
    epc-mode: {{ .Release.Name }}-amf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: {{ .Release.Name }}-amf
  template:
    metadata:
      annotations:
        "cni.projectcalico.org/ipAddrs": "[\"{{ .Values.config.amfIP }}\"]"     
      labels:
        epc-mode:{{ .Release.Name }}-amf
    spec:    
      containers:
        - name: amf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-amfd", "-c", "/open5gs/config-map/amf.yaml"]
          volumeMounts:
          - name: {{ .Release.Name }}-amf-config
            mountPath: /open5gs/config-map/amf.yaml
            subPath: "amf.yaml"
      volumes:
        - name: {{ .Release.Name }}-amf-config
          configMap:
            name: {{ .Release.Name }}-amf-config
