apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-amf-config
  labels:
    epc-mode: {{ .Release.Name }}-amf
data:
  amf.yaml: |
    logger:
        file: /var/log/open5gs/amf.log
        level: debug
        domain: sbi

    amf:
        sbi:
        - addr: 0.0.0.0
          advertise: {{ .Release.Name }}-amf
        ngap:
          dev: {{ .Values.k8s.interface }}
        guami:
          - plmn_id:
              mcc: {{ .Values.config.mcc }}
              mnc: {{ .Values.config.mnc }}
            amf_id:
              region: 2
              set: 0
        tai:
          - plmn_id:
              mcc: {{ .Values.config.mcc }}
              mnc: {{ .Values.config.mnc }}
            tac: {{ .Values.config.tac }}
        plmn_support:
        - plmn_id:
            mcc: {{ .Values.config.mcc }}
            mnc: {{ .Values.config.mnc }}
          s_nssai:
          - sst: {{ .Values.config.sst }}
            sd: {{ .Values.config.sd }}
        security:
            integrity_order : [ NIA2, NIA1, NIA0 ]
            ciphering_order : [ NEA0, NEA1, NEA2 ]
        network_name:
            full: Slice-1
        amf_name: slice-1-amf1

    nrf:
     sbi:
       name: core5g-nrf
