apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pcf-config
  labels:
    epc-mode: {{ .Release.Name }}-pcf
data:
  pcf.yaml: |
    logger:
        file: /var/log/open5gs/pcf.log
    
    db_uri: mongodb://core5g-mongodb-svc/open5gs    

    pcf:
      sbi:     
      - addr: 0.0.0.0
        advertise: {{ .Release.Name }}-pcf
    nrf:
     sbi:
      name: core5g-nrf
