apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pcf
  labels:
    epc-mode: {{ .Release.Name }}-pcf
spec:
  selector:
    epc-mode: {{ .Release.Name }}-pcf
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80  
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pcf-deployment
  labels:
    epc-mode: {{ .Release.Name }}-pcf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: {{ .Release.Name }}-pcf
  template:
    metadata:
      labels:
        epc-mode: {{ .Release.Name }}-pcf
    spec:    
      containers:
        - name: {{ .Release.Name }}-pcf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-pcfd", "-c", "/open5gs/config-map/pcf.yaml"]
          volumeMounts:
          - name: {{ .Release.Name }}-pcf-config
            mountPath: /open5gs/config-map/pcf.yaml
            subPath: "pcf.yaml"          
      volumes:
        - name: {{ .Release.Name }}-pcf-config
          configMap:
            name: {{ .Release.Name }}-pcf-config         
