# Default values for open5gs-epc-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

open5gs:
  image:
    repository: registry.gitlab.com/infinitydon/registry/open5gs-aio
    pullPolicy: IfNotPresent
    tag: "v2.4.5"

ueransim:
   repository: registry.gitlab.com/infinitydon/registry/ueransim
   pullPolicy: IfNotPresent
   tag: "v3.2.6"   
   ue:
     imsi: imsi-208930000000021
     imei: "356938035643803"
     imeiSv: "4370816125816151"
     op: "63bfa50ee6523365ff14c1f45f88737d"
     secKey: "0C0A34601D4F07677303652C0462535B"    

k8swait:
   repository: groundnuty/k8s-wait-for
   pullPolicy: IfNotPresent
   tag: "v1.4" 

dnn2: iot  

#Must be a valid IP with Prefix
pool: "10.46.0.1/16"

#Pool IP to route with IP Tables
route: "10.46.0.0/16"

config:
  upfIP: "slice-1-upf-svc.open5gs.svc.cluster.local"    
  amfIP: "amf-slice-1-sctp.open5gs.svc.cluster.local"
  amfPort: "38412"
  GnbIP: "gnb-slice-1-svc.open5gs.svc.cluster.local"  
  mcc: 208
  mnc: 93
  tac: 7
  sd: 2
  sst: 2

# Primary/Native kubernetes interface
k8s:
 interface: eth0